services:
  backend:
    image: backend
    container_name: blog_b_prod
    env_file:
      - ./part4/.env
    build: 
      dockerfile: Dockerfile
      context: ./part4

    depends_on:
      - mongo
    
  mongo:
      image: mongo
      container_name: blog_mongo
      ports:
      - 3456:27017
      environment:
        MONGO_INITDB_ROOT_USERNAME: adminMeInFirst
        MONGO_INITDB_ROOT_PASSWORD: adminIsInSecond
        MONGO_INITDB_DATABASE: BlogsAndUsers
      volumes: 
        - ./part4/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
        - ./mongo_data:/data/db
  
  app:
    image: front
    build:
      context: ./part5/bloglist-frontend 
      dockerfile: Dockerfile 
    volumes:
      - ./part5/bloglist-frontend:/src/app
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
      
    environment:
    - VITE_BACKEND_URL=http://localhost:8080/
    container_name: front_prod
    depends_on:
      - backend
      - mongo
  debug-helper:
    image: busybox

 
